# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'LinkMoa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'lottie-ios'
  pod 'Moya', '~> 14.0'
  pod 'Kanna', '~> 5.2.2'
  pod 'Kingfisher', '~> 6.0'
  # Include all other configurations except `Debug-M1`
  pod 'GoogleSignIn', :configurations => ['Debug', 'Release']
  # Pods for LinkMoa
end

target 'LinkMoaShareExtension' do
   # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'Moya', '~> 14.0'
  pod 'Kanna', '~> 5.2.2'
  pod 'Kingfisher', '~> 6.0'
end

target 'LinkMoaWidgetExtension' do
   # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya', '~> 14.0'
  pod 'Kingfisher', '~> 6.0'
end
